### ISSUE TITLE
The pump load query for generators appears to return extraneous results

### ISSUE THREAD

**Issue by bradystoll** [NREL/H5PLEXOS.jl#1]
When querying "Pump Load" for generators in R from an h5 database very large and very small numbers (10^-317 etc) appear instead of 0's. This doesn't occur when querying "Pump Load" from the region, or other properties that I've seen from generators.

**Comment by GordStephen** [comment]
Interesting... Do the weird numbers show up in an HDF5 file browser (h5ls, HDFCompass, HDFView) too?

**Comment by GordStephen** [comment]
Closing this for now. Feel free to reopen if you see an issue on the H5PLEXOS side.
