### ISSUE TITLE
Consider switching zip libraries

### ISSUE THREAD

**Issue by GordStephen** [NREL/H5PLEXOS.jl#10]
InfoZIP.jl has always been fragile, trying to use the system zip utilities and then if needed falling back on ZipFile.jl in spite of the fact that it doesn't include it as a dependency. Probably worth investigating if there's a more recent solution (perhaps using _jll libraries) instead.

**Comment by GordStephen** [comment]
Quick search didn't turn up anything new. One option would be to just eliminate InfoZIP.jl and use ZipFile.jl directly. Another would be to develop [libzip](https://libzip.org/)_jll ourselves.

**Comment by dehorsley** [comment]
I have a fork working with just ZipFile.jl that I might be able to upstream. I'm not entirely happy with it however.

Another option is it looks like there is now a [libzip_jll.jl](https://github.com/JuliaBinaryWrappers/libzip_jll.jl).

**Comment by GordStephen** [comment]
Closing this now that we have a solution based on `libzip_jll` (see [here](https://github.com/NREL/H5PLEXOS.jl/issues/20#issuecomment-2392616579)). I'll close the other issues once that branch is merged.
