### ISSUE TITLE
PLEXOS Solution not processing properly (only 5KB in size, with no solution data within)

### ISSUE THREAD

**Issue by craigl33** [NREL/H5PLEXOS.jl#11]
I have been trying to process new runs from an older model (running in P8.3R10), but H5PLEXOS.jl doesn't seem to like the format and does not properly process the .zip file, leading to an empty HDF5 container which is unuseable by h5plexos in Python. 

Is this a known issue?

**Comment by GordStephen** [comment]
No, I don't think we've seen that before. Can you share the full error message that's reported?

**Comment by craigl33** [comment]
This seems to be an issue with one of the diagnostics being included, which i resolved by toggling with the settings. Unfortunately, I am not 100% sure what I did.
