### ISSUE TITLE
Errors when using H5PLEXOS

### ISSUE THREAD

**Issue by xiaofeiwang158** [NREL/H5PLEXOS.jl#12]
Hi, I have the following issue when using H5PLEXOS. Do you know how to fix it?
julia> using H5PLEXOS
[ Info: Precompiling H5PLEXOS [30e9bc9d-95c1-474a-9a40-60ab4bafb5d2]
┌ Warning: InfoZIP falling back to ZipFile.jl backend!
└ @ InfoZIP C:\Users\dafei\.julia\packages\InfoZIP\3AT7m\src\InfoZIP.jl:20
ERROR: LoadError: LoadError: ArgumentError: Package InfoZIP does not have ZipFile in its dependencies:
- If you have InfoZIP checked out for development and have
  added ZipFile as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with InfoZIP

**Comment by GordStephen** [comment]
Hi - yes, we sometimes see this, especially on Windows (this is the motivation behind https://github.com/NREL/H5PLEXOS.jl/issues/10). Usually manually installing ZipFile.jl will solve this (running `add ZipFile` in the package management prompt).

**Comment by m4rz910** [comment]
@GordStephen  Any recommendations on what to try if adding ZipFile doesn't work?

**Comment by akornelis** [comment]
> @GordStephen Any recommendations on what to try if adding ZipFile doesn't work?

Second.

**Comment by m4rz910** [comment]
@akornelis here are my notes detailing how I got it to work. I don't use this anymore so can't check if it still works, but maybe you can?

## Setting Up Julia on windows
* `git clone https://github.com/NREL/H5PLEXOS.jl`
* [Download Julia](https://julialang.org/downloads/)
* Launch Julia
* Launch the package manager by typing ']'
  * FYI you can exit with 'ctrl-c'

1. download and install latest julia
2. clone h5plexos to where you want it.
3. add julia language support in vs code - 
4. restarted vs code and opened to my h5plexos directory
5. started repl ctr+shft+p "julia repl start"
6. pkg> update
7. pkg> registry add https://github.com/NREL/JuliaRegistry.git
8. pkg add H5PLEXOS
	- I get an error here
9. navigate to  the cloned h5plexos folder and 'pkg> activate .'
10. Instantiate (you may get an error if so skip to step 12)
   - I DON'T get an error here
11. using H5PLEXOS (you should get an error here and so skip to step 12)
   - I DO get an error here
11. ensure Manifest.toml has zipfile as a dependency on info zip (~line 58)

[[deps.InfoZIP]]
deps = ["Test", "ZipFile"]
git-tree-sha1 = "087ad2b31892c028b7a56e0a502b13d91faa4b96"
uuid = "f4508453-b816-52ab-a864-26fc7f6211fc"
version = "0.2.0"

12. ensure that Manifest.toml has Zipfile dependencies (~line 212)

[[deps.ZipFile]]
deps = ["Libdl", "Printf", "Zlib_jll"]
git-tree-sha1 = "f492b7fe1698e623024e873244f10d89c95c340a"
uuid = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
version = "0.10.1"

13. Ensure Project.Toml has the ZipFile dependecy (~line 10)
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

14. 'pkg> activate .'
15. 'pkg> instantiate'
16. using H5PLEXOS (good to go!)

**Comment by GordStephen** [comment]
Hey all, I now have a branch that eliminates the InfoZIP dependency and so should fix this. I'm hesitant to merge it immediately given the lack of proper test infrastructure on this package, but if you want to try it for now you can do so with the instructions [here](https://github.com/NREL/H5PLEXOS.jl/issues/20#issuecomment-2392616579).
