### ISSUE TITLE
Apparent change to solution file structure in PLEXOS 9.2

### ISSUE THREAD

**Issue by craigl33** [NREL/H5PLEXOS.jl#13]
Hi Gord

Just to flag an apparent issue with PLEXOS 9.2 where there seems to have been a change to solution file structure, which leads to the following error message in Julia:

```
JuliaError: Exception '<t_class>
    <class_id>1</class_id>
    <name>System</name>
    <class_group_id>1</class_group_id>
    <lang_id>1</lang_id>
  </t_class> does not have child state' occurred while calling julia code:
process("Model THA22_2030plus_NoTOP Solution.zip", "Model THA22_2030plus_NoTOP Solution.h5")
```

I have reached out to EE support to ascertain whether these changes in the solution file are intended/permanent. In the meantime, I'd suggest other users to hold off upgrading to 9.2

Regards,
Craig

**Comment by GordStephen** [comment]
Thanks Craig! Off of the top of my head I don't think `PLEXOSClass.state` data is used for much, so we can always make it optional if necessary.

**Comment by craigl33** [comment]
Hi Gord

So this what I got back from the developers at EE:

> The developers say the issue appears to be that NREL’s code is expecting a <state> tag but it doesn’t exist. This is likely a bug in NREL’s code. The table in question (t_class) does have a state field, and this has not been removed in 9.2. However, in XML datasets, if the value for the field is NULL, the tag is simply omitted. They expect that NREL’s code is not handling the case where there is no state tag, which is valid and indicates the value for the state field is NULL.
> Please let me know if this information helps resolve your query.

Hope this maybe helps

**Comment by GordStephen** [comment]
Makes sense to me. Should be easy enough to make the state field optional on our end too.

**Comment by craigl33** [comment]
Great stuff Gord. Let me know if you need any help with this in terms of testing, etc.

**Comment by GordStephen** [comment]
I just pushed some changes to [PLEXOSUtils.jl](https://github.com/NREL/PLEXOSUtils.jl) - if you manually install the master branch of that package you should get them applied when you use H5PLEXOS:

`pkg> add PLEXOSUtils.jl#master`

That should, in theory, fix the issue, although I don't have any problematic systems to test against. At least, it doesn't appear to have broken any of my existing test systems. Let me know if things look good, and if so, I'll officially tag the new version so it gets used automatically by others.

**Comment by craigl33** [comment]
I have just installed the update and my problematic solution file (from P9.2R01) can now be processed! Thanks for pushing these changes! 

Thanks Gord!
