### ISSUE TITLE
fallback to ZipFile.jl?

### ISSUE THREAD

**Issue by llavin13** [NREL/H5PLEXOS.jl#15]
I just reinstalled H5PLEXOS.jl locally because HPC is unavailable (cry). I noticed when I follow the instructions I seem to get conflicts with InfoZIP when compiling H5PLEXOS. I can get around them by doing `] add ZipFile`, then I get the below

`┌ Warning: InfoZIP falling back to ZipFile.jl backend!`
...

and things work. Should this be so?

**Comment by GordStephen** [comment]
Yes, that's normal for Windows. Glad the fallback worked for you, it seems to be hit-and-miss for many (e.g. #12)

**Comment by llavin13** [comment]
Cool! Should've looked at the other issue. I'll close this one. Thanks!
