### ISSUE TITLE
KeyError: key "t_phase_1" not found

### ISSUE THREAD

**Issue by gdemaere-ECK400** [NREL/H5PLEXOS.jl#2]
When trying on a Plexos solution files (with only a LT plan), I got the following error :" 
ERROR: KeyError: key "t_phase_1" not found
Stacktrace:
 [1] getindex(h::Dict{String, PLEXOSUtils.PLEXOSTable}, key::String)
   @ Base .\dict.jl:482
 [2] PLEXOSUtils.PLEXOSSolutionDatasetSummary(xml::EzXML.Document)
   @ PLEXOSUtils C:\Users\ECK400\.julia\packages\PLEXOSUtils\ksQEQ\src\PLEXOSSolutionDatasetSummary.jl:27
 [3] PLEXOSUtils.PLEXOSSolutionDataset(xml::EzXML.Document)
   @ PLEXOSUtils C:\Users\ECK400\.julia\packages\PLEXOSUtils\ksQEQ\src\PLEXOSSolutionDataset.jl:33
 [4] open_plexoszip(zippath::String)
   @ PLEXOSUtils C:\Users\ECK400\.julia\packages\PLEXOSUtils\ksQEQ\src\utils.jl:3
 [5] #process#1
   @ C:\Users\ECK400\.julia\packages\H5PLEXOS\LyEqe\src\process.jl:6 [inlined]
 [6] process(zipfilein::String, h5fileout::String)
   @ H5PLEXOS C:\Users\ECK400\.julia\packages\H5PLEXOS\LyEqe\src\process.jl:6
 [7] top-level scope
   @ REPL[10]:1
"""

**Comment by GordStephen** [comment]
Yeah, LT solutions are essentially not supported or tested against. I don't think that would be too hard to fix, though. Do you have (or could you create) a toy example solution that you could upload here?

**Comment by GordStephen** [comment]
This error should no longer occur with PLEXOSUtils v0.1.5. I've also updated the h5plexos spec to v0.6.1 to add extra metadata on interval-block mappings, which should be useful for interpreting block-level non-chronological results. I'll close this issue once this package implements v0.6.1 of the spec.

**Comment by GordStephen** [comment]
Ok, this package should now process LT files successfully and save out metadata about interval->block mappings. Closing this issue, but feel free to re-open it if you still have issues.
