### ISSUE TITLE
h5plexos not getting installed

### ISSUE THREAD

**Issue by athatte-rmi** [NREL/H5PLEXOS.jl#20]
Hi Gord,

My name is Amogh Thatte. I recently finished my PhD in the AES program at Mines-NREL. During my PhD, I greatly benefited from converting zip files to H5 files and working with them to automate Plexos post-processing. 

I have started working for RMI and am trying to implement the same workflow as NREL.

However, I need your help to install h5plexos using Julia.  I am following the instructions given on [this page](https://github.com/NREL/H5PLEXOS.jl/blob/master/README.md).  There is an issue with the InfoZip dependency (not sure about the root cause, though). 

Below is the stack trace that I get.  I will be grateful to you for any help in getting me past this point in installation!

Thank you!

 Compat `Julia` not listed in `deps`, `weakdeps` or `extras` section at "C:\\Users\\amogh.thatte\\.julia\\packages\\InfoZIP\\3AT7m\\Project.toml".
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\Types.jl:70
  [2] validate(project::Pkg.Types.Project; file::String)
    @ Pkg.Types C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\project.jl:115
  [3] validate
    @ C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\project.jl:77 [inlined]
  [4] Pkg.Types.Project(raw::Dict{String, Any}; file::String)
    @ Pkg.Types C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\project.jl:137
  [5] Project
    @ C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\project.jl:120 [inlined]
  [6] read_project(f_or_io::String)
    @ Pkg.Types C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\project.jl:154
  [7] fixup_ext!(env::Pkg.Types.EnvCache, pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.Operations C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\Operations.jl:174
  [8] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, new_git::Set{Base.UUID}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform)
    @ Pkg.Operations C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\Operations.jl:1391
  [9] add
    @ C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\Operations.jl:1377 [inlined]
 [10] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::@Kwargs{io::Base.TTY})
    @ Pkg.API C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\API.jl:278
 [11] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::@Kwargs{})
    @ Pkg.API C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\API.jl:159
 [12] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\API.jl:148
 [13] add
    @ C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\API.jl:147 [inlined]
 [14] try_prompt_pkg_add(pkgs::Vector{Symbol})
    @ Pkg.REPLMode C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\REPLMode\REPLMode.jl:729
 [15] #invokelatest#2
    @ .\essentials.jl:892 [inlined]
 [16] invokelatest
    @ .\essentials.jl:889 [inlined]
 [17] check_for_missing_packages_and_run_hooks(ast::Any)
    @ REPL C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\REPL\src\REPL.jl:174
 [18] eval_user_input(ast::Any, backend::REPL.REPLBackend, mod::Module)
    @ REPL C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\REPL\src\REPL.jl:145
 [19] repl_backend_loop(backend::REPL.REPLBackend, get_module::Function)
    @ REPL C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\REPL\src\REPL.jl:246
 [20] start_repl_backend(backend::REPL.REPLBackend, consumer::Any; get_module::Function)
    @ REPL C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\REPL\src\REPL.jl:231
 [21] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool, backend::Any)
    @ REPL C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\REPL\src\REPL.jl:389
 [22] run_repl(repl::REPL.AbstractREPL, consumer::Any)
    @ REPL C:\Users\amogh.thatte\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\REPL\src\REPL.jl:375
 [23] (::Base.var"#1013#1015"{Bool, Bool, Bool})(REPL::Module)
    @ Base .\client.jl:432
 [24] #invokelatest#2
    @ .\essentials.jl:892 [inlined]
 [25] invokelatest
    @ .\essentials.jl:889 [inlined]
 [26] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
    @ Base .\client.jl:416
 [27] exec_options(opts::Base.JLOptions)
    @ Base .\client.jl:333
 [28] _start()
    @ Base .\client.jl:552

**Comment by GordStephen** [comment]
Hi Amogh - Yes, this is a known issue on Windows (#10, #12) - I've been meaning to get to this for a while, let me see what I can do...

**Comment by GordStephen** [comment]
So I _think_ we might finally have a resolution to this. I just pushed a branch to PLEXOSUtils that uses a different (non-broken) Zip library. For now, until it's better tested, you'll need to manually install that branch of PLEXOSUtils, and then try installing H5PLEXOS:

```
add PLEXOSUtils#gs/libzip
add H5PLEXOS
```

I don't currently have access to many PLEXOS outputs to test with at the moment, but if that does work, go ahead and try converting some results, and report back with any issues...

**Comment by athatte-rmi** [comment]
Hi Gord,

Thanks a lot! I tested it on a couple of solution files, and it seems to work great.

I appreciate your quick help in getting it done.

Can you please update the documentation with this step in your free time? It would be beneficial for people using Windows OS.

**Comment by GordStephen** [comment]
Great to hear! I'll try to solicit some more testing on this end too, and then will tag a new version of PLEXOSUtils, so that the special installation instructions aren't necessary.
