### ISSUE TITLE
KeyError: key "t_custom_column" not found

### ISSUE THREAD

**Issue by mike-welch** [NREL/H5PLEXOS.jl#3]
```julia
julia> process("Model RD - Multi-Year Load Solution.zip", "test.h5")
ERROR: KeyError: key "t_custom_column" not found
Stacktrace:
 [1] getindex(h::Dict{String, PLEXOSUtils.PLEXOSTable}, key::String)
   @ Base .\dict.jl:482
 [2] PLEXOSUtils.PLEXOSSolutionDatasetSummary(xml::EzXML.Document)
   @ PLEXOSUtils C:\Users\TelosEnergy\.julia\packages\PLEXOSUtils\ksQEQ\src\PLEXOSSolutionDatasetSummary.jl:27
 [3] PLEXOSUtils.PLEXOSSolutionDataset(xml::EzXML.Document)
   @ PLEXOSUtils C:\Users\TelosEnergy\.julia\packages\PLEXOSUtils\ksQEQ\src\PLEXOSSolutionDataset.jl:33
 [4] open_plexoszip(zippath::String)
   @ PLEXOSUtils C:\Users\TelosEnergy\.julia\packages\PLEXOSUtils\ksQEQ\src\utils.jl:3
 [5] #process#1
   @ C:\Users\TelosEnergy\.julia\packages\H5PLEXOS\LyEqe\src\process.jl:6 [inlined]
 [6] process(zipfilein::String, h5fileout::String)
   @ H5PLEXOS C:\Users\TelosEnergy\.julia\packages\H5PLEXOS\LyEqe\src\process.jl:6
 [7] top-level scope
   @ REPL[10]:1
```

I have a PLEXOS model that has several custom columns defined on the generator objects appending useful metadata for downstream analysis, such as the EIA ID. I think this data existing may be the source of the error observed here and interested in feedback on workarounds/solutions. Happy to provide additional information on request.

**Comment by GordStephen** [comment]
Interesting, I didn't know custom columns were a thing! If you can send me some sample output that includes custom columns, I should be able to add support for them.

**Comment by mike-welch** [comment]
This is where it's a little weird for me... AFAIK the data from the custom columns is only available for use on the input side. Any time I've needed any of that data I've done it in Excel after doing some copy/pasting. If you see something different it would be great to know!

It's fairly straight-forward to add a custom column through the Settings menu:
![image](https://user-images.githubusercontent.com/19764934/135904621-cfd07b19-902d-4a92-bab9-e05cf15267df.png)

Name it whatever you like and add as many as you want. If my hypothesis is correct, the existence of one or more custom columns will mess up your code.

**Comment by GordStephen** [comment]
Ok, thanks, I'll do some tests. If we don't need to do anything with the data (other than not crash when it exists), it should be an easy fix.

**Comment by GordStephen** [comment]
Looks like all the column values are actually available in the solution XML (as `t_memo_object` tags). I'll update PLEXOSUtils.jl to read in that information, although for now I won't write it out to HDF5 files here. It could be done in the future, though.

**Comment by GordStephen** [comment]
@mike-welch can you try running `update` in the package management prompt (you should see PLEXOSUtils updated to v0.1.4) and see if this works for you now?

**Comment by mike-welch** [comment]
Almost crossed messages with you... I had installed `PLEXOSUtils.jl` from source and got past this error. 

---

However, I'm now looking at another one... 

```julia
julia> process("Model RD - Multi-Year Load Solution.zip", "test.h5")
ERROR: BoundsError: attempt to access 2-element Vector{PLEXOSUtils.PLEXOSSample} at index [-2]
Stacktrace:
 [1] setindex!(A::Vector{PLEXOSUtils.PLEXOSSample}, x::PLEXOSUtils.PLEXOSSample, i1::Int64)
   @ Base .\array.jl:839
 [2] PLEXOSUtils.PLEXOSSolutionDataset(xml::EzXML.Document)
   @ PLEXOSUtils C:\Users\TelosEnergy\.julia\packages\PLEXOSUtils\7xbC1\src\PLEXOSSolutionDataset.jl:53
 [3] open_plexoszip(zippath::String)
   @ PLEXOSUtils C:\Users\TelosEnergy\.julia\packages\PLEXOSUtils\7xbC1\src\utils.jl:3
 [4] #process#1
   @ C:\Users\TelosEnergy\.julia\packages\H5PLEXOS\LyEqe\src\process.jl:6 [inlined]
 [5] process(zipfilein::String, h5fileout::String)
   @ H5PLEXOS C:\Users\TelosEnergy\.julia\packages\H5PLEXOS\LyEqe\src\process.jl:6
 [6] top-level scope
   @ REPL[5]:1
```

The case linked noted is an intermediate solution file downloaded from PLEXOS Connect. In this situation, it's part 1 of 20 in of a 20 sample job (split by sample). I found another case that was run (rightfully or wrongfully) with a Stochastic object applied that sets 1 variable sample and got the same error. I then went and found a 8 sample case that successfully merged and got the same error, but stating "9-element vector" instead of "2". 🤷

**Comment by GordStephen** [comment]
Ok, interesting. I've split your comment out into a new issue, we can discuss there. I'll close this issue since the original problem seems to be resolved.
