### ISSUE TITLE
ERROR: BoundsError: attempt to access 0-element Vector{PLEXOSUtils.PLEXOSPeriod0} at index [1]

### ISSUE THREAD

**Issue by drfrode1** [NREL/H5PLEXOS.jl#5]
Running on Julia 1.6.3 (Docker:latest)

I am getting a  BoundsError: attempt to access 0-element Vector{PLEXOSUtils.PLEXOSPeriod0} at index [1] when trying to process file

###Content of zip file
-rw-r--r--  3.0 unx    96574 tx defF 21-Oct-21 10:35 ModelLT.txt
-rw-r--r--  3.0 unx 51881339 tx defF 21-Oct-21 10:35 ModelLT.xml
drwxr-xr-x  3.0 unx        0 bx stor 21-Oct-26 15:44 Month/
drwxr-xr-x  3.0 unx        0 bx stor 21-Oct-26 15:44 Year/
-rw-r--r--  3.0 unx    40300 tx defF 21-Oct-21 10:18 id2name.csv
-rw-r--r--  3.0 unx 82742688 bx defF 21-Oct-21 10:35 t_data_3.BIN
-rw-r--r--  3.0 unx  6895224 bx defF 21-Oct-21 10:35 t_data_4.BIN

###Stacktrace:
 [1] getindex
   @ ./array.jl:805 [inlined]
 [2] PLEXOSUtils.PLEXOSPhase1(e::EzXML.Node, d::PLEXOSUtils.PLEXOSSolutionDataset)
   @ PLEXOSUtils ~/.julia/packages/PLEXOSUtils/gozgd/src/types.jl:393
 [3] PLEXOSUtils.PLEXOSSolutionDataset(xml::EzXML.Document)
   @ PLEXOSUtils ~/.julia/packages/PLEXOSUtils/gozgd/src/PLEXOSSolutionDataset.jl:53
 [4] open_plexoszip(zippath::String)
   @ PLEXOSUtils ~/.julia/packages/PLEXOSUtils/gozgd/src/utils.jl:3
 [5] #process#1
   @ ~/.julia/packages/H5PLEXOS/Ab3he/src/process.jl:6 [inlined]
 [6] process(zipfilein::String, h5fileout::String)
   @ H5PLEXOS ~/.julia/packages/H5PLEXOS/Ab3he/src/process.jl:6
 [7] top-level scope
   @ REPL[16]:1

###Warnings:
┌ Warning: InfoZIP falling back to ZipFile.jl backend!
└ @ InfoZIP ~/.julia/packages/InfoZIP/3AT7m/src/InfoZIP.jl:20
┌ Warning: Package InfoZIP does not have ZipFile in its dependencies:
│ - If you have InfoZIP checked out for development and have
│   added ZipFile as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with InfoZIP
└ Loading ZipFile into InfoZIP from project dependency, future warnings for InfoZIP are suppressed.

**Comment by GordStephen** [comment]
I've just pushed some updates that should avoid the original issue here, so I'll close this now. If after updating you still see the problem, feel free to re-open.
