### ISSUE TITLE
Possible version mismatch

### ISSUE THREAD

**Issue by netr0m** [NREL/H5PLEXOS.jl#8]
https://github.com/NREL/H5PLEXOS.jl/blob/bece0eb4b5e036791493119ff4e727ebc00ca09a/Project.toml#L4
https://github.com/NREL/H5PLEXOS.jl/blob/bece0eb4b5e036791493119ff4e727ebc00ca09a/src/H5PLEXOS.jl#L12

**Comment by GordStephen** [comment]
That's down to the difference between the Julia package version and the [h5plexos file format](https://github.com/h5plexos/h5plexos-spec) version (which is accessed from multiple packages across different languages) - the Julia package will sometimes be updated without changing the file format.
